#!/usr/bin/env bash

# ==================================================================
# bb-functions
# ==================================================================
# BB-Functions Library File
#
# File:         bb-functions
# Author:       Ragdata
# Date:         15/04/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
# PREFLIGHT
# ==================================================================
